name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: mganik-system
  REGION: asia-southeast2
  SERVICE_NAME: mganik-wasepje-service
  REPO_NAME: wasepje-repo
  IMAGE_NAME: wasepje

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure gcloud
        run: gcloud config set project $PROJECT_ID

      - name: Build & Push Docker image to Artifact Registry
        run: |
          gcloud auth configure-docker $REGION-docker.pkg.dev --quiet
          docker build -t $REGION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$IMAGE_NAME .
          docker push $REGION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$IMAGE_NAME

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy $SERVICE_NAME \
            --image=$REGION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$IMAGE_NAME \
            --platform=managed \
            --region=$REGION \
            --allow-unauthenticated \
            --port=3000
